fluttergems/awesome-open-source-flutter-apps

README.md

This closes #22 
**Added InnerQuest project link under productivity section.**
InnerQuest is an app designed to help you embark on a journey of self-discovery, personal growth, and increased productivity. This Flutter-based application offers a unique blend of features that are tailored to your individual personality type.

Added  InnerQuest Project link

---

README.md

**Added explr project link under books section.**
**Explr is built with flutter and dart .**
Explr is the project  for all book lovers who want to find other book lovers to either exchange books, discuss about books or get to know people who have similar preference when it comes to reading.
.

Added Explr project 

---

README.md

Added a open-source Finance app build with Flutter

---

README.md

Added reflectly,watermaniac in health and fitness---natrium in finance---inkino in entertainment

Updated README.md as per issue#20

---

README.md

added Toughest (app) in education

Update README.md as per issue #32

---

README.md

Added more open source flutter apps

---

README.md

This closes #40 
**Learn**, a simple learning app built using Flutter for kids. This app is designed to provide an engaging learning experience for children, covering a wide range of topics including :
- A-Z Alphabets with examples and pronunciation.
- Animals and their pronunciation along with their voices.
- Body parts and their pronunciation with Short information on various topics.

Added Learn Flutter App Project

---

README.md

added Platypus Crypto in finance

Update README.md as per issue#42

---

README.md

added orientation application to education field

Update README.md as per issue #44

---

README.md

Update README.md as per issue #48

---

README.md

Update README.md as per issue #49

---

README.md

Update README.md as per issue #50

---

README.md

Update README.md as per issue #59

---

README.md

Update README.md as per issue #60

---

README.md

Update README.md as per issue #64

---

README.md

Fixes #76 
Added budgeto in the finance category

Update README.md as per issue #76

---

README.md

Fixes #85 
Added Mathematics app in the education category
Fixes #88  
Added EcoMateSG in the Lifestyle category

Update README.md as per issue #85 and #88

---

README.md

Fixes #92 
Added Meditation app in the Health And Fitness category

Update README.md as per issue #92

---

README.md

Fixes #93 
Added Arcade Plaza in Games and fun category
@ashitaprasad  please review and merge this pull request

Update README.md as per issue #93

---

README.md

Update README.md as per issue #65

---

README.md

Update README.md as per issue #66

---

README.md

Update README.md as per issue #67

---

README.md

Fixes #87 
Added sudoku-flutter in Games and Fun category

Update README.md as per Issue #87

---

README.md

Fixes #101 
Added Openreads in Productivity

Update README.md as per issue #101

---

README.md

added math metrix app into games field

Update README.md as per issue #84

---

README.md

Fixes #103 
Added flixquest to entertainment category

Update README.md as per issue #103

---

README.md

Fixes #105
Added wavybeats to music category

Update README.md as per issue #105

---

README.md

Fixes #112 
Added AnimSearch in Anime & Manga

Update README.md as per issue #112

---

README.md

Fixes #113 
Added localsend in Network, Bluetooth & Sharing

Update README.md as per issue #113

---

README.md

Fixes #104 
Added watch in the entertainment category

Update README.md as per issue #104

---

README.md

Fixes #106 
Added eqTrainer in the education category

Update README.md as per issue #106

---

README.md

added open source flutter app 'FLUTTER_NewsApp'

---

README.md

added open source flutter app 'SportsTeamManagementFlutter'

---

README.md

added open source flutter app 'shoot-report-flutter'

---

README.md

added open source flutter app 'LifeSync'

---

README.md

Fixes #138 
Added Responsive Flutter Portfolio in Portfolio Category
assign me this pull request

Update README.md as per issue #138

---

README.md

Added habo a habit tracker app 

---

README.md

added open food facts in health and fitness field

Update README.md as per issue#81

---

README.md

Inkino flutter app added
reame file updated
fixes : #136 
github repo : [https://github.com/roughike/inKino](https://github.com/fluttergems/awesome-open-source-flutter-apps/issues/url)

added open source flutter app "inkino"

---

README.md

added open source flutter app "MedRem"

---

README.md

added the open source project OpenNutriTracker

---

README.md

Fixes #150 
Added Seeds Light Wallet in Finance Category 

Update README.md as per issue #150

---

README.md

just added open source twitter clone project using flutter
Fixes #149 
repo link :https://github.com/TheAlphamerc/flutter_twitter_clone?tab=readme-ov-file

added new open source flutter app "Fwitter"

---

README.md

Fixes #135 
@ashitaprasad please review and merge this PR 
Also, please add level1 and gssoc labels
Thank you!

added open source flutter app 'studyu'

---

README.md

Adding Track My Indoor Workout to the Health & Fitness category

---

README.md

Fixes #159
Added Prayer in Religion Category

Update README.md as per issue #159

---

README.md

Fixes #167 
Added E Quran App in Religion Category

Update README.md as per issue #167

---

README.md

add open source project

---

README.md

add a open source project

---

README.md

Fixes #176 
Added FlareLine in Admin Dashboard Category

Update README.md as per issue #176

---

README.md

added open source flutter app "fitconnect"

---

README.md

added criminal catcher

---

README.md

added a weather app in weather section

---

README.md

Fixes #185 
@ashitaprasad 
Please review and merge this pull request

Added Quiz app in education

---

README.md

added open source flutter app "business_light"

---

README.md

add a open source project "Flews"

---

README.md

add a open source project "Flight search"

---

README.md

added an open source project- Auragita
Category- Religion
Closes #201

added an open source project - fixes issue #201

---

README.md

add a open source project-Flutter AudioBooks

---

README.md

added open source project-Boilerplate Project+DigiDiagnose

---

README.md

add open source project- Safe Bump

---

README.md

added open source project- EncryptX

---

README.md

want to add open-source project flutter-tetris #223

---

README.md

Want to Add HangMan Game Flutter #224

---

README.md

added open source project- browser app

---

README.md

Want to add Dino Run game #229

---

README.md

Added Club Penguin Game
Closes #230

Want to add Club Penguin Game #230

---

README.md

Added BananaMon Game
Closes #231

Want to add bananaMon Game #231

---

README.md

added open source project

---

README.md

add a open source project "ShareACab" 

---

README.md

add a open source project "Fluttery Filmy"

---

README.md

add a open source project "Food Delivery App" 

---

README.md

Added fruit ninja game link #247

want to add fruit ninja game link #247

---

README.md

add a open source project "QuitSmoke"

---

README.md

I've added a flutter Dinasaur Game .
Closes : #256

Added Flutter project 

---

README.md

add a open source project "Time Cop"

---

README.md

I've added the tic tac toe game 
CLoses : #264

Added Tic Tac Toe game 

---

README.md

added project- flutter_crush

---

README.md

Add 2048 Game #266

---

README.md

Add Image editor app #267

---

README.md

added-  Virlow Flutter Recorder

---

README.md

Add Kunai Game #277

---

README.md

added- Flutter League

---

README.md

Add Chatgpt flutter #280

---

README.md

Add Storify app #285

---

README.md

Add ai assistance app #284 

---

README.md

Closes #291 
This adds a flutter tetris game.

Adds Tetris

---

README.md

Adds minesweeper game

---

README.md

Fixes #303 
Added flutter wger in Health & Fitness Category

Update README.md as per issue #303

---

README.md

Add pacman game

---

README.md

Add Flappy-Bird Game

---

README.md

Added code quizzy game

---

README.md

Adds new flutter game Quokka

---

README.md

Adds tapit flutter game

---

README.md

Added doodle game

---

README.md

Fixes #327 
Added flutter Weather App in  Weather  Category

Update README.md as per issue #327

---

README.md

added- flutter games

---

README.md

Add marvel app #299

---

README.md

added- AppFlowy

---

README.md

added- Fedi

---

README.md

Adds new game - "Quards"

---

README.md

Adds new flutter game-"type"

---

README.md

added project- one second diary

---

README.md

added project- bhagavad gita

---

README.md

Adds SuperMario game based on the Flutter flame game engine

---

README.md

added- AirDash

---

README.md

Add darkness dungeon game

---

README.md

Adds new flutter game-"wordlyPlus"

---

README.md

Adds "Cocola James" Game

---

README.md

added - NetworkArch

---

README.md

added- LaCoro

---

README.md

added- ai assistant app

---

README.md

added finance project

---

README.md

Added FindSeat

---

README.md

added- Anti-cheat exam app

---

README.md

added- Plant Disease Detector

---

README.md

Fixes # 400 
Added flutter Shop App in Shopping & E-commerce  Category

 Update README.md as per issue #400

---

README.md

added- flutter scribble

---

README.md

added- Talawa

---

README.md

Added Whatsapp Clone app in Chat and messaging category
Closes #423

Added Whatsapp Clone App

---

README.md

#427 added etaka a Mobile Financial Mobile Application based on P2P Banking Concept for Android and iOS Platform

added etaka

---

README.md

Fixes #415 
Added Flutter Anki Clone in Others Category

Update README.md as per issue #415

---

README.md

Added invoice pdf generator
Issue #426

Added invoice pdf generator

---

README.md

Added Todoey app in Productivity
Closes #430

Added Todoey App

---

README.md

Added CrunchyAnime app in Anime
Closes #432

Added CrunchyAnime app

---

README.md

added movie db app getx

---

README.md

add spiritual song book

---

README.md

Added Car controller

---

README.md

add a open source project "Chat-Messaging" 

---

README.md

added librum - A free and open-source Bible verse reference app.
Closes #513

Added librum

---

README.md

Closes #514  A simple and awesome Udemy Clone made with Flutter, using sensational Responsiveness Techniques.
A clone made for study and learning

Added fludemy

---

README.md

add puzzle game

---

README.md

Added Pocket Music Player in Music category
Closes #448

Added Pocket Music Player App

---

README.md

Added Marina.Moda App in Music Category
Closes #449

Added Marina.Moda App

---

README.md

add a open source project "Hacki"

---

README.md

add a open source project "ai_radio"

---

README.md

add a open source project "Your Journal"

---

README.md

Added FlutCrack in Utilities Category
Closes #450

Added FlutCrack App

---

README.md

Added Deep waste app in Lifestyle
Closes #489

Added Deep waste app 

---

README.md

Added Neumorphic Calculator in Productivity
Closes #488

Added Neumorphic Calculator

---

README.md

Model–View–ViewModel (MVVM) is a very established architectural pattern
closes #529

added mvvm setup

---

README.md

closes #472
repo link : https://github.com/CyBear-Jinni/cbj_app

added open source project CyBear Jinni App

---

README.md

Added Convapp

---

README.md

An open-source online learning platform
#540

added cloudmate

---

README.md

E-learning app where students can share their doubts wiith their peers they can chat and also they can find their notes
#541

added academic master

---

README.md

a gamified learning app for higher math
#542

added mathebuddy

---

README.md

Add nyrna app #566

---

README.md

Added Live Score App for wear OS #567

Add Live Score App for wear OS #567

---

README.md

add a open source project "Flutter-Photography-Application" 

---

README.md

Added an entry under the "Chat & Messaging" category. Closes #592.

Add Talktive

---

README.md

Added the TapAway

---

README.md

closes #608 
Under education - https://github.com/bernardoveras/studle - Application for students to research their data and performance at school

added studle

---

README.md

About
Private, cross-platform package tracking app 
closes #591

Libretrack 

---

README.md

Added Ejimo App 

---

README.md

Added LifeList App
Closes #601

Added LifeList app

---

README.md

Added Monekin App

---

README.md

Added climbing-gym-app(GripGuide)

---

README.md

Added Time Tracking app with Flutter & Firebase
https://github.com/bizz84/starter_architecture_flutter_firebase
closes #470

Update README.md by adding Time Tracking app with Flutter & Firebase 

---

README.md

https://github.com/dstark5/Openlib
An Open source app to download and read books from shadow library 
#562

Update README.md added openlib

---

README.md

Added Firestaurant

---

README.md

A wrist-worn device and monitoring system with user-file-memory management system for a person with Body-focused Repetitive Behavior
#626

added BFRBSys

---

README.md

Adds PING PONG game

---

README.md

#643
https://github.com/CCExtractor/taskwarrior-flutter
This is the repo of mobile app of taskwarrior

Added taskwarrior flutter

---

README.md

@ashitaprasad 
Repo: https://github.com/imrofayel/Ozan/

Added Ozan - a personal knowledge base inspired from Obsidian built on flutter.

---

README.md

Thanks for your response
this is PR for updated readme and added MindWrite to Lifestyle category
issue #666

update and added MindWrite to lifestyle

---

README.md

@ashitaprasad please review this pr

Add Group track app

---

README.md

Add WidgetHub

---

README.md

https://github.com/fluttergems/awesome-open-source-flutter-apps/issues/675

Added Tomo, Pomodoro app for MacOS

---

README.md

Apexo is a flutter application that helps dentists and assistants manage their dental clinics, it supports appointment scheduling, multiple doctors, permissions, works offline, synchronizes across multiple devices when online, secure and fail safe.
It's also free and open-source.
Website: https://apexo.app
Repo: https://github.com/alselawi/apexo-flutter
Docs: https://docs.apexo.app/
Demo https://demo.apexo.app/

added Apexo

---

README.md

TMDB app
TruthOrDare & Charades game app

Add two apps

---

README.md

Replace of Spooky (old repo name).

Add StoryPad

---

README.md

Hello! This PR is created for the purpose of adding Board Buddy to your repository. Board Buddy is your ultimate board game companion. Issue [#699](https://github.com/fluttergems/awesome-open-source-flutter-apps/issues/699)
Links:
- **[App Store](https://apps.apple.com/app/board-buddy-score-counter/id6743980638)**
- [**Google Play**](https://play.google.com/store/apps/details?id=com.khlebobul.board_buddy)  
- [**GitHub repo**](https://github.com/khlebobul/board_buddy)  
- [**Official site**](https://boardbuddyapp.vercel.app/)

Add Board Buddy

---

README.md

Add TriPeaks NEUE

---

README.md

Add HireHub a job seeking application in business category

Add HireHub 

---

README.md

This PR adds  SavourAI, an open-source Flutter application, to the Food & drink section of the awesome Flutter apps list.
- App Name: SavourAI
- GitHub Repo: https://github.com/Dheeraj-Chintala/Android-Apps/tree/master/savourai
- Description: This app delivers a dynamic, swipeable feed of random meals using public API TheMealDB with necessary credits, Think of it as a Reels-style food discovery experience, complete with YouTube recipe links, ingredient lists, and more!
- Packages:  
http: ^1.4.0
flutter_animate: ^4.5.2
crystal_navigation_bar: ^1.0.4
iconly: ^1.0.1
palette_generator: ^0.3.3+7
url_launcher: ^6.3.1
advanced_search: ^2.2.5
flutter_markdown: ^0.7.7+1
google_fonts: ^6.2.1
cached_network_image: ^3.4.1
package_info_plus: ^8.3.0
lottie: ^3.3.1
- License: MIT  
Let me know if any …

Added SavourAI Flutter App to awesome list.

---

README.md

Added 5 New Open-Source Projects.
Projects added are the following :
1. Ruko – ⚒️ Tools & Utilities
2. Cards – 🎉 Games & Fun
3. Echo MPD – 🎵 Music
4. FloatingVolume – ⚒️ Tools & Utilities
5. Tautulli Remote – 📡 IoT & Remote Control

Added new Projects
